apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblioteka-cn-deployment
spec:
  selector:
    matchLabels:
      app: biblioteka-cn-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: biblioteka-cn-deployment
    spec:
      containers:
        - name: mdb
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "bibliotekacn123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
            - name: cndb-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
        # containers:
        - name: biblioteka-cn
          image: aleksapapovic/biblioteka_cn:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ASPNETCORE_HTTPS_PORTS
              value: "8081"
          ports:
            - containerPort: 8080
            - containerPort: 8081
          readinessProbe:
            exec:
              command:
                ["psql", "-w", "-U", "postgres", "-d", "cndb", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                ["psql", "-w", "-U", "postgres", "-d", "cndb", "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: user-secrets
              mountPath: /home/app/.microsoft/usersecrets
              readOnly: true
            - name: aspnet-https
              mountPath: /home/app/.aspnet/https
              readOnly: true

      volumes:
        - name: cndb-storage
          persistentVolumeClaim:
            claimName: cndb-pvc
        - name: init-script
          configMap:
            name: cndb-init-script
        - name: user-secrets
          hostPath:
            path: /path/to/your/local/usersecrets
        - name: aspnet-https
          hostPath:
            path: /path/to/your/local/aspnet/https
---
apiVersion: v1
kind: Service
metadata:
  name: cndb
spec:
  type: ClusterIP
  selector:
    component: biblioteka-cn-deployment
  ports:
    - name: http
      port: 8080
      targetPort: 9000
    - name: https
      port: 8081
      targetPort: 9001
    - name: db
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cndb-init-script
data:
  init-db.sh: "set -e; psql -v ON_ERROR_STOP=1 <<-EOSQL    CREATE DATABASE mdb;EOSQL"
