apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblioteka-ni-deployment
  labels:
    app: biblioteka-ni-deployment
spec:
  selector:
    matchLabels:
      app: biblioteka-ni-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: biblioteka-ni-deployment
    spec:
      containers:
        - name: mdb
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "bibliotekani123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
            - name: nidb-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
        - name: biblioteka-ni
          image: aleksapapovic/biblioteka_ek:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            # - name: ASPNETCORE_HTTPS_PORTS
            #   value: "8081"
            - name: CONNECTION
              value: "nidb-k8"
          ports:
            - containerPort: 8080
            # - containerPort: 8081
          # volumeMounts:
          #   - name: user-secrets
          #     mountPath: /home/app/.microsoft/usersecrets
          #     readOnly: true
          #   - name: aspnet-https
          #     mountPath: /home/app/.aspnet/https
          #     readOnly: true

      volumes:
        - name: nidb-storage
          persistentVolumeClaim:
            claimName: nidb-pvc
        - name: init-script
          configMap:
            name: nidb-init-script
        # - name: user-secrets
        #   hostPath:
        #     path: C:/Users/papov/AppData/Roaming/Microsoft/UserSecrets
        # - name: aspnet-https
        #   hostPath:
        #     path: C:/Users/papov/AppData/Roaming/ASP.NET/Https
---
apiVersion: v1
kind: Service
metadata:
  name: nidb
  labels:
    app: nidb
spec:
  # type: ClusterIP
  selector:
    app: biblioteka-ni-deployment
  ports:
    - name: http
      port: 9030
      targetPort: 8080
    # - name: https
    #   port: 8081
    #   targetPort: 9031
    # - name: db
    #   port: 5432
    #   targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nidb-init-script
data:
  init-db.sh: "set -e; psql -v ON_ERROR_STOP=1 <<-EOSQL    CREATE DATABASE mdb;EOSQL"
