apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblioteka-ns-deployment
spec:
  selector:
    matchLabels:
      app: biblioteka-ns-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: biblioteka-ns-deployment
    spec:
      containers:
        - name: mdb
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "bibliotekans123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
            - name: nsdb-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
        - name: biblioteka-ns
          image: aleksapapovic/biblioteka_ek:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            # - name: ASPNETCORE_HTTPS_PORTS
            #   value: "8081"
            - name: CONNECTION
              value: "nsdb-k8"
          ports:
            - containerPort: 8080
            # - containerPort: 8081
          # volumeMounts:
          #   - name: user-secrets
          #     mountPath: /home/app/.microsoft/usersecrets
          #     readOnly: true
          #   - name: aspnet-https
          #     mountPath: /home/app/.aspnet/https
          #     readOnly: true

      volumes:
        - name: nsdb-storage
          persistentVolumeClaim:
            claimName: nsdb-pvc
        - name: init-script
          configMap:
            name: nsdb-init-script
        # - name: user-secrets
        #   hostPath:
        #     path: C:/Users/papov/AppData/Roaming/Microsoft/UserSecrets
        # - name: aspnet-https
        #   hostPath:
        #     path: C:/Users/papov/AppData/Roaming/ASP.NET/Https
---
apiVersion: v1
kind: Service
metadata:
  name: nsdb
spec:
  type: ClusterIP
  selector:
    component: biblioteka-ns-deployment
  ports:
    - name: http
      port: 8080
      targetPort: 9010
    # - name: https
    #   port: 8081
    #   targetPort: 9011
    - name: db
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nsdb-init-script
data:
  init-db.sh: "set -e; psql -v ON_ERROR_STOP=1 <<-EOSQL    CREATE DATABASE mdb;EOSQL"
