name: Docker Image CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push the BibliotekaCentralna image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./Biblioteka/BibliotekaCentralna/
          push: true
          tags: aleksapapovic/biblioteka_cn

      - name: Push the BibliotekaEkspozitura image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./Biblioteka/BibliotekaEkspozitura/
          push: true
          tags: aleksapapovic/biblioteka_ek
